version: "3.7"

networks:
  development:
    external: true
    name: development

volumes:
  pg_data:

services:
  postgres:
    image: postgres:latest
    hostname: postgres
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - development
